apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- keycloak-deployment.yaml
- keycloak-service.yaml
- jarvis-auth-default-networkpolicy.yaml

images:
- name: jarvis
  newName: lucasgoisdev/jarvis-auth
  newTag: f868adf68b8ded2f50a824d1ce201f5a3213f554
- name: jarvis-auth
  newName: lucasgoisdev/jarvis-auth
  newTag: latest
